<?php
$successMsg = $block->getSuccessMsg();
$enable = $block->getEnable();
$stockDetail = $block->getStockDetail();
$user = $block->getUser();
$checkLogin = $this->helper('Softnoesis\Asktoexpert\Helper\Data')->isLoggedIn();
$customerId     = $block->getCustomerId();
$customerEmail  = $block->getCustomerEmail();
$customerName   = trim($block->getCustomerName());
$product = $block->getCurrentProduct();
$productId = $product->getId();
$productName = $product->getName();
$productSku  = $product->getSku();
$stockQuantity = $block->getStockItem($productId, $product->getStore()->getWebsiteId());
$stockStatus = $stockQuantity->getIsInStock();
$productQty =  $stockQuantity->getQty();
?>
<?php
$flag = 0;
if ($enable == 1) {
    if ($checkLogin == 1) {

        if ($stockQuantity->getData('is_in_stock') == 1 && $product->isSaleable() == 1) {
            if ($user == 'register') {
                if ($stockDetail == 'instock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
            if ($user == 'all') {
                if ($stockDetail == 'instock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
        }
        if ($stockQuantity->getData('is_in_stock') != 1 && $product->isSaleable() != 1) {
            if ($user == 'register') {
                if ($stockDetail == 'outofstock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
            if ($user == 'all') {
                if ($stockDetail == 'outofstock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
        }
    }
    if ($checkLogin != 1) {

        if ($stockQuantity->getData('is_in_stock') == 1 && $product->isSaleable() == 1) {
            if ($user == 'guest') {
                if ($stockDetail == 'instock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
            if ($user == 'all') {
                if ($stockDetail == 'instock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
        }
        if ($stockQuantity->getData('is_in_stock') != 1 && $product->isSaleable() != 1) {
            if ($user == 'guest') {
                if ($stockDetail == 'outofstock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
            if ($user == 'all') {
                if ($stockDetail == 'outofstock') {
                    $flag = 1;
                }
                if ($stockDetail == 'all') {
                    $flag = 1;
                }
            }
        }
    }
}
?>
<?php if ($flag == 1):?>
    <button title="<?= /* @noEscape */  __('Ask To Expert') ?>" 
        class="action primary" 
        id="request-quote" 
        type="button">
        <span><?= /* @noEscape */ __('Ask question') ?></span>
    </button>
<?php endif; ?>
<div id="customer_quote_data" name="customer_quote_data">
    <span class="success_msg"></span>
    <?php if ($checkLogin = 1): ?>
        <div class="request_field">
            <label class="required" for="name">
                <?= /* @noEscape */ __('Enter Your Name') ?><em>*</em>
            </label>
            <div class="input-box">
                    <input type="text" class="input-text required-entry form-control" title="customer_name" id="guest_quote_customer"name="quote_customer" size="35" value="<?php echo $customerName;?>" <?php if (isset($customerName) && $customerName!='') { echo "disabled"; }?> />
                <span class="quotecustomer-error"></span>
            </div>
        </div>
        <div class="request_field email">
            <label class="required" for="email">
                <?= /* @noEscape */ __('Enter Your Email') ?><em>*</em>
            </label>
            <div class="input-box">
                <input type="text" class="input-text required-entry form-control" 
                title="customer_email" id="guest_quote_email" name="quote_email" size="35" value="<?php echo $customerEmail;?>" <?php if (isset($customerEmail) && $customerEmail!='') { echo "disabled"; }?> />
                <span class="quoteemail-error"></span>
                <span class="quotemail-error"></span>
            </div>
        </div>
    <?php endif; ?>
    <div class="request_field">
        <label class="required" for="name"><?= /* @noEscape */ __('Enter Your Contact Number ') ?>
            <em>*</em>
        </label>
        <div class="input-box">
            <input type="number" class="input-text required-entry form-control" 
            title="quote-qty" id="guest_quote_qty" name="quote-qty" size="35" min="1" />
            <span class="quantity-error"></span>
        </div>
    </div>
    <div class="request_field">
        <label class="required" for="comment"><?= /* @noEscape */ __('Comment') ?></label>
        <div class="input-box">
            <textarea rows="3" cols="5" 
                class="required-entry input-text form-control" 
                id="guest_quote_desc" 
                name="quote-desc" 
                placeholder="<?= /* @noEscape */ __('Enter Description') ?>"
            ></textarea>
        </div>
        <input type=hidden id="loggedin" value=<?= /* @noEscape */ $checkLogin;?> />
        <input type=hidden id="product_name" value="<?= /* @noEscape */ $productName;?>" />
        <input type=hidden id="product_sku" value="<?= /* @noEscape */ $productSku;?>" />
        <?php if ($checkLogin == 1):?>      
        <input type=hidden id="login_customer_name" value="<?= /* @noEscape */ $customerName;?>" />       
        <input type=hidden id="login_customer_email" value="<?= /* @noEscape */ $customerEmail;?>" />       
        <input type=hidden id="login_customer_id" value="<?= /* @noEscape */ $customerId;?>" />       
        <?php endif; ?>
        <input type=hidden id="message" value= "<?= /* @noEscape */ $successMsg;?>" /> 
        <input type=hidden id="qty_msg" value= "<?= /* @noEscape */ __('Please enter your contact number..!') ?>" />
        <input type=hidden id="customer_msg" value= "<?= /* @noEscape */ __('Please enter your name..!') ?>" />
        <input type=hidden id="email_msg" value= "<?= /* @noEscape */ __('Please enter your email..!') ?>" />
        <input type=hidden id="valid_msg" value= "<?= /* @noEscape */ __('Please enter valid email..!') ?>" />
        <input type=hidden id="popup_title" value= "<?= /* @noEscape */ __('Ask To Expert') ?>" />
        <input type=hidden id="popup_submit" value= "<?= /* @noEscape */ __('Submit') ?>" />
        <div class="loader-main" style="display: none;"><img src="<?php echo $block->getViewFileUrl('Softnoesis_Asktoexpert::images/loader.gif'); ?>" /></div>
    </div>
</div>

<script>
    require(
        [
        'jquery',
        'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
            ) {
            var popup_title = jQuery("#popup_title").val(); 
            var popup_submit = jQuery("#popup_submit").val(); 
            var options = {  
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: popup_title,
                buttons: [{
                    text:popup_submit,
                    class: '',
                    click: function() {
                        $(".loader-main").css("display", "block");
                        var sEmail = jQuery("#guest_quote_email").val(); 
                        var qtyMsg = jQuery("#qty_msg").val();
                        var nameMsg = jQuery("#customer_msg").val(); 

                        var emilMsg = jQuery("#email_msg").val();
                        var validMsg = jQuery("#valid_msg").val(); 
                        var filter = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;
                        var isLoggedin = jQuery('#loggedin').val();                        
                        var successMsg = jQuery('#message').val();

                        var guest_quote_customer = jQuery("#guest_quote_customer").val(); 

                        if(guest_quote_customer==''){
                            //jQuery(".quantity-error").html('');
                            jQuery(".quotecustomer-error").html(nameMsg);
                        }else{
                            jQuery(".quotecustomer-error").html('');
                        }
                        if(sEmail==''){                           
                           jQuery(".quoteemail-error").html(emilMsg);
                        }else{
                            jQuery(".quoteemail-error").html('');
                        }
                        if(sEmail!='' && filter.test(sEmail) == false){  
                            jQuery(".quotemail-error").html(validMsg);
                        }else{
                            jQuery(".quotemail-error").html();
                        }

                        if (jQuery("#guest_quote_qty").val() == "") {                   
                            jQuery(".quantity-error").html(qtyMsg);
                        }else if(jQuery("#guest_quote_customer").val() == ' ') {
                            jQuery(".quantity-error").html('');
                            jQuery(".quotecustomer-error").html(nameMsg);
                        } else if (isLoggedin != 1 && sEmail == '') {
                            jQuery(".quotecustomer-error").html('');
                            jQuery(".quoteemail-error").html(emilMsg);
                        } else if (isLoggedin != 1 && sEmail != '' && filter.test(sEmail) == false) {
                            jQuery(".quoteemail-error").html('');
                            jQuery(".quotemail-error").html(validMsg);
                        } else {
                            jQuery(".quantity-error").html('');
                            jQuery(".quotecustomer-error").html('');
                            jQuery(".quotemail-error").html('');
                            jQuery(".quotemail-error").html(''); 
                            jQuery.ajax({ 
                                url: "<?= /* @noEscape */ $block->getUrl('askforquote/askforquote/quote/index') ?>",
                                showLoader: true,
                                data: {
                                    'guest_quote_qty': jQuery("#guest_quote_qty").val(),
                                    'guest_quote_customer': jQuery("#guest_quote_customer").val(),
                                    'guest_quote_email': jQuery("#guest_quote_email").val(),
                                    'guest_quote_desc': jQuery("#guest_quote_desc").val(),
                                    'login_customer_name': jQuery("#login_customer_name").val(),
                                    'login_customer_email': jQuery("#login_customer_email").val(),
                                    'login_customer_id': jQuery("#login_customer_id").val(),
                                    'product_name': jQuery("#product_name").val(),
                                    'product_sku': jQuery("#product_sku").val(),
                                    'guest_product_id': <?= /* @noEscape */ $productId; ?>
                                },
                                type: 'POST'
                            }).done(function(data) {
                                $(".loader-main").css("display", "none");
                                jQuery(".success_msg").html(successMsg);
                                setTimeout(function() {
                                    jQuery(".success_msg").fadeOut();
                                    jQuery("#guest_quote_qty").val('');
                                    jQuery("#guest_quote_customer").val('');
                                    jQuery("#guest_quote_email").val('');
                                    jQuery("#guest_quote_desc").val('');
                                    $("#customer_quote_data").modal("closeModal");
                                }, 3000);
                            });
                        }
                    }
                }]
            };
            var popup = modal(options, $('#customer_quote_data'));
            $("#request-quote").on('click', function() {
                $("#customer_quote_data").modal("openModal");
            });
            $("#popup_submit").click(function(){
            $('.modal-footer').addClass('loader-new');
          });

        }
        );
    </script>
